import json
from typing import Annotated
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, ToolMessage
from langchain_core.tools import InjectedToolArg, tool
from langchain_openai import ChatOpenAI
import requests

# Load environment variables (e.g., OPENAI_API_KEY)
load_dotenv()


# 1. Define the first tool to fetch the conversion rate
@tool
def get_conversion_factor(base_currency: str, taget_currency: str) -> str:
    """Fetches the currency conversion factor between two currencies from ExchangeRate-API."""
    url = f"https://v6.exchangerate-api.com/v6/84ae3c663df18e543b56444c/pair/{base_currency}/{taget_currency}"
    response = requests.get(url)
    # Return text so it can be easily parsed with json.loads() later
    return response.text


# 2. Define the second tool to calculate the converted amount
@tool
def convert(
    base_currency_value: int,
    conversion_rate: Annotated[float, InjectedToolArg],
) -> float:
    """Calculates the target currency amount based on the base currency value and conversion rate."""
    return base_currency_value * conversion_rate


# 3. Initialize the LLM and bind both tools
llm = ChatOpenAI(model="gpt-4o-mini")
llm_with_tools = llm.bind_tools([get_conversion_factor, convert])

# 4. Set up the initial conversation history
messages = [
    HumanMessage(
        content="What is the conversion factor between USD and INR and based on that can you convert 110 usd to inr?"
    )
]

# Get the AI's response which will include the tool calls
ai_message = llm_with_tools.invoke(messages)
messages.append(ai_message)  # Append AI message containing tool calls to history

print("--- Tool Calls Generated by LLM ---")
print(ai_message.tool_calls)
print("-" * 40)

conversion_rate = None

# 5. Execute the tool calls sequentially
for tool_call in ai_message.tool_calls:
    print(f"Executing tool: {tool_call['name']}")

    if tool_call["name"] == "get_conversion_factor":
        # Invoke the tool with arguments provided by the LLM
        tool_message1 = get_conversion_factor.invoke(tool_call["args"])

        # Parse the JSON string response to extract the specific conversion rate
        data = json.loads(tool_message1)
        conversion_rate = data.get("conversion_rate")

        # Append the tool result back into the message history as a ToolMessage
        messages.append(
            ToolMessage(content=tool_message1, tool_call_id=tool_call["id"])
        )

    elif tool_call["name"] == "convert":
        # Inject the dynamically fetched conversion rate into the tool arguments
        if conversion_rate is not None:
            tool_call["args"]["conversion_rate"] = conversion_rate

        # Invoke the convert tool
        tool_message2 = convert.invoke(tool_call["args"])

        # Append the conversion result to the message history
        messages.append(
            ToolMessage(
                content=str(tool_message2), tool_call_id=tool_call["id"]
            )
        )

# 6. Get the final response from the LLM using the updated conversation history
final_response = llm_with_tools.invoke(messages)

print("\n--- Final LLM Response ---")
print(final_response.content)
